PAGE = r'''<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PAC-Harness · ToUser 工作台</title>
<style>
:root{font-family:Inter,"Segoe UI","Microsoft YaHei",sans-serif;color:#20332e;background:#f3f5f2}*{box-sizing:border-box}body{margin:0}button,input,textarea,select{font:inherit}button{cursor:pointer;border:1px solid #cdd8d1;border-radius:8px;background:white;padding:10px 16px;color:#253c32}button:hover{background:#e8efe9}button:disabled{opacity:.45;cursor:default}.primary{background:#25654c;color:white;border-color:#25654c}.primary:hover{background:#194e39}header{height:76px;border-bottom:1px solid #dbe3dc;display:flex;align-items:center;justify-content:space-between;padding:0 30px;background:#fff}header b{font-size:21px;letter-spacing:1px}header small{margin-left:18px;color:#6c7c73}.layout{display:grid;grid-template-columns:minmax(360px,1fr) 310px;min-height:calc(100vh - 76px)}main{padding:28px;min-width:0}.inspector{background:#fafbf9;border-left:1px solid #dbe3dc;padding:26px 20px;overflow:hidden}h1{font-size:26px;margin:0 0 8px}h2{font-size:16px;margin:24px 0 12px}p,small{line-height:1.7}.muted{color:#6c7c73;font-size:13px}.badge{font-size:12px;padding:5px 9px;background:#e5ede7;border-radius:20px;display:inline-block}#chat{height:calc(100vh - 340px);min-height:260px;overflow:auto;margin:22px 0;scrollbar-gutter:stable}.message{white-space:pre-wrap;overflow-wrap:anywhere;padding:16px 20px;margin:12px 0;border-radius:12px;background:white;border:1px solid #e0e6df;line-height:1.65}.message.user{background:#e0eee5;margin-left:32px}.role{font-size:11px;color:#688373;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px}.composer{border:1px solid #cdd8d1;background:white;border-radius:12px;padding:12px}textarea{width:100%;resize:vertical;min-height:84px;border:0;padding:8px;outline:none;background:transparent}.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}input,select{width:100%;padding:11px;border:1px solid #cdd8d1;border-radius:8px;background:white;margin:6px 0 12px}label{font-size:13px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.6;max-height:400px;overflow:auto}summary{cursor:pointer;font-size:13px;overflow-wrap:anywhere;margin:12px 0}#error{color:#9b3528;white-space:pre-wrap;font-size:13px}#rootpath{word-break:break-all}#notice{padding:12px 0}.empty{padding:35px 20px;background:#ebf0ea;border-radius:12px;line-height:1.9}footer{margin-top:24px;font-size:12px;color:#708077}@media(max-width:1050px){.layout{grid-template-columns:1fr}.inspector{grid-column:1/-1;border-top:1px solid #dbe3dc}}@media(max-width:650px){header{padding:16px;height:auto}header small{display:none}.layout{display:block}main{padding:18px}#chat{height:400px}}
</style>
<header><div><b>PAC-Harness <span style="color:#52836c">/</span> 工作台</b><small>项目与知识，从一次对话开始</small></div><span class="badge">本地 · ToUser</span></header>
<div class="layout">
<main><div class="actions"><div><h1 id="title">ToUser 项目协助</h1><div class="muted" id="rootpath"></div></div><span id="status" class="badge">尚未开始</span></div>
<div id="chat"></div><div class="composer"><textarea id="message" placeholder="描述需求、补充接口信息，或请 ToUser 修改项目…"></textarea><div class="actions"><small class="muted">支持多行输入 · Ctrl / ⌘ + Enter 发送</small><button id="send" class="primary">发送给 ToUser</button></div></div><div class="actions" id="notice"><small class="muted">修改会经过现有离线验证后应用。请先停止当前业务任务。</small><button id="close">结束协助</button></div><div id="error" role="alert"></div></main>
<section class="inspector"><div class="muted">协助记录</div><h2>会话历史</h2><select id="history" aria-label="会话历史"></select><button id="fresh">新一轮协助</button><p class="muted">刷新可查看已保存的对话。服务重启后开启新一轮协助；历史记录不会丢失。</p><h2>修改与验证</h2><div id="audit" class="muted">暂无修改记录</div><h2>运行说明</h2><p class="muted">此版本用于当前项目协助，不接管正在运行的 CLI 任务。配置适配器和模型后，在项目目录启动任务。</p><pre id="command"></pre><p class="muted">如修改了 pac_harness，请重启工作台以加载新代码。</p></section></div>

<script>
const $=id=>document.getElementById(id);let token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('workbench-token');if(token)sessionStorage.setItem('workbench-token',token);history.replaceState(null,'',location.pathname);
let sid=null,sessions=[],rendered='',pending=false,historyKey='',auditKey='';
const labels={busy:'ToUser 正在处理',waiting:'等待你的回复',closing:'处理完成后结束',finished:'已结束',error:'发生错误',interrupted:'服务中断'};
async function api(path,data){let r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{'X-Workbench-Token':token||'','Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});let v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v}
function error(e){$('error').textContent=e.message}
function draw(){let s=sessions.find(s=>s.id===sid);$('status').textContent=s?labels[s.status]:'尚未开始';$('send').disabled=pending||Boolean(s&&s.status!=='waiting');$('close').disabled=!s||!['waiting','busy'].includes(s.status);let text=JSON.stringify(s?.messages||[]);if(text!==rendered){let near=$('chat').scrollHeight-$('chat').scrollTop-$('chat').clientHeight<100;rendered=text;$('chat').replaceChildren();if(!s){let el=document.createElement('div');el.className='empty';el.textContent='直接描述你的问题、需要保存的知识，或希望构建的 Skill。';el.style.whiteSpace='pre-line';$('chat').append(el)}for(const m of s?.messages||[]){let el=document.createElement('div');el.className='message '+m.role;let role=document.createElement('div');role.className='role';role.textContent=m.role==='user'?'你':'ToUser';let content=document.createElement('div');content.textContent=m.content;el.append(role,content);$('chat').append(el)}if(near)$('chat').scrollTop=$('chat').scrollHeight}}
async function refresh(){let data=await api('state',{});sessions=data.history;if(sid===null&&sessions.length)sid=sessions[0].id;let hk=JSON.stringify(sessions.map(s=>[s.id,s.status]));if(hk!==historyKey){historyKey=hk;$('history').replaceChildren();for(const s of sessions){let op=document.createElement('option');op.value=s.id;op.textContent=(s.messages.find(m=>m.role==='user')?.content||'会话').slice(0,22)+' · '+labels[s.status];$('history').append(op)}}$('history').value=sid||'';let ak=JSON.stringify(data.audit);if(ak!==auditKey){auditKey=ak;$('audit').replaceChildren();if(!data.audit.length)$('audit').textContent='暂无修改记录';for(const a of data.audit){let d=document.createElement('details'),summary=document.createElement('summary'),p=document.createElement('pre');summary.textContent=a.path;p.textContent=a.text;d.append(summary,p);$('audit').append(d)}}draw()}
$('history').onchange=()=>{sid=$('history').value;rendered='';draw()};$('fresh').onclick=()=>{let active=sessions.find(s=>['busy','waiting','closing'].includes(s.status));if(active){sid=active.id}else{sid='new'}rendered='';draw();$('message').focus()};
$('send').onclick=async()=>{if(pending)return;let message=$('message').value;if(!message.trim())return;pending=true;draw();try{if(!sessions.some(s=>s.id===sid)){sid=(await api('start',{message})).id}else{await api('send',{id:sid,message})}$('message').value='';sessionStorage.removeItem('touser-draft');$('error').textContent='';await refresh()}catch(e){error(e)}finally{pending=false;draw()}};
$('message').oninput=()=>sessionStorage.setItem('touser-draft',$('message').value);$('message').value=sessionStorage.getItem('touser-draft')||'';
$('message').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();if(!$('send').disabled)$('send').click()}};
$('close').onclick=async()=>{try{await api('close',{id:sid});await refresh()}catch(e){error(e)}};
(async()=>{try{let project=await api('project');$('rootpath').textContent=project.path;$('command').textContent='python -m pac_harness --task "你的任务" --preview';await refresh()}catch(e){error(e)}})();setInterval(()=>refresh().catch(error),2000);
</script></html>'''